/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clavis.Windows;

import javax.swing.JDialog;

/**
 *
 * @author toze
 */
public class NewJPanel extends JDialog {

    
    private final javax.swing.JComponent componentepai;
    private java.awt.Color painelcor;
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        componentepai = null;
        this.add(jPanelInicial);
        init();
    }
    
    public NewJPanel(javax.swing.JComponent comp, java.awt.Color cor) {
        componentepai = comp;
        painelcor = cor;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();

        jPanelInicial.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(painelcor, 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanelInicial.setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the painelcor
     */
    public java.awt.Color getPainelcor() {
        return painelcor;
    }
    
    public void init(){
        initComponents();
        this.add(jPanelInicial);
    }

    /**
     * @param painelcor the painelcor to set
     */
    public void setPainelcor(java.awt.Color painelcor) {
        this.painelcor = painelcor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelInicial;
    // End of variables declaration//GEN-END:variables
}
