/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clavis.Windows;

import Clavis.ButtonListRequest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author toze
 */
public class WListMaterial extends javax.swing.JFrame {

    private Color corborda;
    private Color corfundo;
    private static String url;
    private static Langs.Locale lingua;
    private List<Keys.TypeOfMaterial> tiposdematerial;
    private Keys.TypeOfMaterial tiposelecionado;
    private static Clavis.RequestList requisicoes;
    private static ButtonListRequest btrequests;

    public WListMaterial(Color corfundo, Color corborda, String url, Langs.Locale lingua, Clavis.RequestList req) {
        this.corborda = corborda;
        this.corfundo = corfundo;
        this.url = url;
        this.lingua = lingua;
        tiposelecionado = null;
        tiposdematerial = new java.util.ArrayList<>();
        requisicoes = req;
        btrequests = null;
    }

    public void makePanel() {
        Border b = BorderFactory.createLineBorder(corborda, 4);
        jPanelInicial.setBorder(BorderFactory.createCompoundBorder(b, BorderFactory.createLineBorder(Color.BLACK)));
        jPanelInicial.setBackground(corfundo);
    }

    public void appear() {
        java.awt.Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Point po = new java.awt.Point((int) dim.getWidth() / 2 - this.getWidth() / 2, (int) dim.getHeight() / 2 - this.getHeight() / 2);
        this.setLocation(po);
        this.setVisible(true);
    }

    public void makeFirstTabs() {
        if ((requisicoes != null)&&(requisicoes.isConnected())) {
            jTabbedPaneMaterialBotoes.removeAll();
            btrequests = new ButtonListRequest(url, this, requisicoes, lingua, jTabbedPaneMaterialBotoes, 2);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Todos"), btrequests.getScrollPane());
            btrequests = new ButtonListRequest(url, this, requisicoes, lingua, jTabbedPaneMaterialBotoes, 0);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Livres"), btrequests.getScrollPane());
            btrequests = new ButtonListRequest(url, this, requisicoes, lingua, jTabbedPaneMaterialBotoes, 1);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Ocupados"), btrequests.getScrollPane());
        }
    }

    public void create() {
        initComponents();
        makePanel();
        
        makeFirstTabs();
    }
    
    public static javax.swing.JTabbedPane getTable(){
        return jTabbedPaneMaterialBotoes;
    }
    
    
    public static void updateTables(javax.swing.JFrame frame){
        if ((requisicoes != null)&&(requisicoes.isConnected())) {
            jTabbedPaneMaterialBotoes.removeAll();
            btrequests = new ButtonListRequest(url, frame, requisicoes, lingua, jTabbedPaneMaterialBotoes, 2);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Todos"), btrequests.getScrollPane());
            btrequests = new ButtonListRequest(url, frame, requisicoes, lingua, jTabbedPaneMaterialBotoes, 0);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Livres"), btrequests.getScrollPane());
            btrequests = new ButtonListRequest(url, frame, requisicoes, lingua, jTabbedPaneMaterialBotoes, 1);
            jTabbedPaneMaterialBotoes.add(lingua.translate("Ocupados"), btrequests.getScrollPane());
        }
    }

    /**
     * This met
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jScrollPaneMaterialBotoes = new javax.swing.JScrollPane();
        jTabbedPaneMaterialBotoes = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2222222, 2147483647));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanelInicial.setBackground(new java.awt.Color(254, 254, 254));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelInicial.setPreferredSize(new java.awt.Dimension(800, 500));

        jScrollPaneMaterialBotoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneMaterialBotoes.setOpaque(false);
        jScrollPaneMaterialBotoes.setPreferredSize(new java.awt.Dimension(540, 528));

        jTabbedPaneMaterialBotoes.setBackground(new java.awt.Color(254, 254, 254));
        jTabbedPaneMaterialBotoes.setOpaque(true);
        jTabbedPaneMaterialBotoes.setPreferredSize(new java.awt.Dimension(574, 490));
        jScrollPaneMaterialBotoes.setViewportView(jTabbedPaneMaterialBotoes);
        UIManager.put("TabbedPane.background", Color.WHITE);
        UIManager.put("TabbedPane.selected", Color.red);

        jTabbedPaneMaterialBotoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTabbedPaneMaterialBotoes.setAutoscrolls(true);

        jTabbedPaneMaterialBotoes.setFocusable(false);

        jTabbedPaneMaterialBotoes.setOpaque(true);

        jTabbedPaneMaterialBotoes.setRequestFocusEnabled(false);

        jScrollPaneMaterialBotoes.setViewportView(jTabbedPaneMaterialBotoes);

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(592, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(592, 30));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(592, 30));

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMaterialBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMaterialBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText(lingua.translate("Lista de recursos"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WListMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WListMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WListMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WListMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WListMaterial wr = new WListMaterial(new Color(255, 255, 255), new Color(125, 234, 145), "", Langs.Locale.getLocale_pt_PT(),null);
                wr.create();
                wr.appear();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JScrollPane jScrollPaneMaterialBotoes;
    private static javax.swing.JTabbedPane jTabbedPaneMaterialBotoes;
    // End of variables declaration//GEN-END:variables
}
