/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clavis.Windows;

import TimeDate.Date;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Calendar;
import java.util.Collections;
import java.util.prefs.Preferences;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author toze
 */
public class WRequest extends javax.swing.JFrame {

    private static final java.awt.Color BACKGROUND_COLOR = new java.awt.Color(255, 255, 255);
    private static final java.awt.Color BORDER_COLOR = new java.awt.Color(115, 115, 115);

    private final java.awt.Color corborda;
    private final java.awt.Color corfundo;
    private final Langs.Locale lingua;
    private final Keys.Material mat;
    private final String url;
    private javax.swing.JSpinner.NumberEditor spineditor;
    private java.util.List<Keys.TypeOfMaterial> tlista;
    private java.util.Set<Keys.Material> mlista;
    private Preferences prefs;
    boolean entrou;
    Timer tim;

    /**
     * Creates new form WRequest
     */
    public WRequest() {
        super();
        corborda = BORDER_COLOR;
        corfundo = BACKGROUND_COLOR;
        lingua = Langs.Locale.getLocale_pt_PT();
        mat = null;
        url = "";
        tlista = new java.util.ArrayList<>();
        mlista = new java.util.TreeSet<>();
        spineditor = null;
        prefs = Preferences.userNodeForPackage(getClass());
    }

    public WRequest(java.awt.Color corborda, java.awt.Color corfundo, String url, Langs.Locale lingua) {
        super();
        this.corborda = corborda;
        this.corfundo = corfundo;
        this.lingua = lingua;
        mat = null;
        this.url = url;
        tlista = new java.util.ArrayList<>();
        mlista = new java.util.TreeSet<>();
        spineditor = null;
        prefs = Preferences.userNodeForPackage(getClass());
    }

    public WRequest(java.awt.Color corborda, java.awt.Color corfundo, String url, Langs.Locale lingua, Keys.Material mat) {
        super();
        this.corborda = corborda;
        this.corfundo = corfundo;
        this.lingua = lingua;
        this.mat = mat;
        this.url = url;
        tlista = new java.util.ArrayList<>();
        mlista = new java.util.TreeSet<>();
        spineditor = null;
        prefs = Preferences.userNodeForPackage(getClass());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRecurso = new javax.swing.JLabel();
        jComboBoxTipoMaterial = new Components.PersonalComboBox(jLabelRecurso);
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMaterial = new Components.PersonalComboBox(jLabelRecurso);
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerQuantidade = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelPessoa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxNomeUtilizador = new Components.PersonalComboBox(jLabelRecurso);
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCodigoUtilizador = new Components.PersonalComboBox(jLabelRecurso);
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel6 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSpinner2 = new javax.swing.JSpinner(new SpinnerDateModel());
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));

        jPanelInicial.setBackground(new java.awt.Color(254, 254, 254));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanelInicial.setName(""); // NOI18N
        jPanelInicial.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanelInicial.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(227, 233, 238));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setCornerSize(6);
        dropShadowBorder1.setShadowSize(3);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder1, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel1.setMinimumSize(new java.awt.Dimension(424, 250));

        jLabelRecurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setCornerSize(6);
        dropShadowBorder2.setShadowSize(3);
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jLabelRecurso.setBorder(dropShadowBorder2);
        jLabelRecurso.setMinimumSize(new java.awt.Dimension(47, 30));
        jLabelRecurso.setName(""); // NOI18N
        jLabelRecurso.setPreferredSize(new java.awt.Dimension(47, 30));

        jComboBoxTipoMaterial.setMinimumSize(new java.awt.Dimension(35, 30));
        jComboBoxTipoMaterial.setPreferredSize(new java.awt.Dimension(35, 30));

        jLabel2.setMaximumSize(new java.awt.Dimension(4444444, 26));
        jLabel2.setMinimumSize(new java.awt.Dimension(104, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(104, 26));

        jComboBoxMaterial.setHelpText(lingua.translate("Escolha de recurso")+" ...");
        jComboBoxMaterial.setMinimumSize(new java.awt.Dimension(35, 30));
        jComboBoxMaterial.setPreferredSize(new java.awt.Dimension(35, 30));
        jComboBoxMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaterialActionPerformed(evt);
            }
        });

        jLabel3.setMaximumSize(new java.awt.Dimension(444444, 26));
        jLabel3.setMinimumSize(new java.awt.Dimension(104, 26));
        jLabel3.setPreferredSize(new java.awt.Dimension(104, 26));

        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(3333337, 26));
        jLabel5.setMinimumSize(new java.awt.Dimension(104, 26));
        jLabel5.setPreferredSize(new java.awt.Dimension(104, 26));

        jSpinnerQuantidade.setMinimumSize(new java.awt.Dimension(32, 26));
        jSpinnerQuantidade.setPreferredSize(new java.awt.Dimension(32, 26));

        jButton1.setBackground(new java.awt.Color(51, 102, 153));
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(90, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipoMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelRecurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabelRecurso.setText(lingua.translate("Recurso"));
        jComboBoxTipoMaterial.setBackgroundColor(new Color(213,213,213));
        jComboBoxTipoMaterial.setHelpText("Tipo de material");
        jComboBoxTipoMaterial.create();
        jLabel2.setText(lingua.translate("Tipo de material")+": ");
        jComboBoxMaterial.create();
        jLabel3.setText(lingua.translate("Recurso específico")+": ");
        jLabel5.setText(lingua.translate("Quantidade")+": ");
        try {
            if (Clavis.KeyQuest.class.getResource("Images/searchbranco.png") != null) {
                BufferedImage im = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/searchbranco.png"));
                ImageIcon ic = new ImageIcon(im);
                jButton1.setIcon(ic);
            } else {
                jButton1.setText(lingua.translate("Pesquisa"));
            }
        } catch(IOException e){}

        jPanel2.setBackground(new java.awt.Color(245, 242, 236));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setCornerSize(6);
        dropShadowBorder3.setShadowSize(3);
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowRightShadow(false);
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder3, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel2.setMinimumSize(new java.awt.Dimension(424, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(424, 250));

        jLabelPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setCornerSize(6);
        dropShadowBorder4.setShadowSize(3);
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        jLabelPessoa.setBorder(dropShadowBorder4);
        jLabelPessoa.setMinimumSize(new java.awt.Dimension(47, 30));
        jLabelPessoa.setName(""); // NOI18N
        jLabelPessoa.setPreferredSize(new java.awt.Dimension(47, 30));

        jLabel8.setToolTipText("");
        jLabel8.setMaximumSize(new java.awt.Dimension(374444, 26));
        jLabel8.setMinimumSize(new java.awt.Dimension(37, 26));
        jLabel8.setPreferredSize(new java.awt.Dimension(147, 26));

        jComboBoxNomeUtilizador.setMinimumSize(new java.awt.Dimension(35, 30));
        jComboBoxNomeUtilizador.setPreferredSize(new java.awt.Dimension(35, 30));
        jComboBoxNomeUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomeUtilizadorActionPerformed(evt);
            }
        });

        jLabel11.setMaximumSize(new java.awt.Dimension(433332, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(129, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(129, 30));

        jComboBoxCodigoUtilizador.setMinimumSize(new java.awt.Dimension(35, 30));
        jComboBoxCodigoUtilizador.setPreferredSize(new java.awt.Dimension(35, 30));
        jComboBoxCodigoUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCodigoUtilizadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNomeUtilizador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCodigoUtilizador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxNomeUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCodigoUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelPessoa.setText(lingua.translate("Utilizador"));
        jLabel8.setText(lingua.translate("Nome de utilizador")+": ");
        jComboBoxNomeUtilizador.setBackgroundColor(new Color(213,213,213));
        jComboBoxNomeUtilizador.setHelpText(lingua.translate("Nome de utilizador")+" ...");
        jComboBoxNomeUtilizador.create();
        jLabel11.setText(lingua.translate("Código")+": ");
        jComboBoxCodigoUtilizador.setBackgroundColor(new Color(213,213,213));
        jComboBoxCodigoUtilizador.setHelpText(lingua.translate("Código na instituição")+" ...");
        jComboBoxCodigoUtilizador.create();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(100, 100, 100));
        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hora");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setMaximumSize(new java.awt.Dimension(3343446, 96));
        jLabel7.setMinimumSize(new java.awt.Dimension(36, 26));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setCornerSize(6);
        dropShadowBorder5.setShadowSize(3);
        dropShadowBorder5.setShowLeftShadow(true);
        jSpinner1.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder5, javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0))));
        jSpinner1.setMinimumSize(new java.awt.Dimension(50, 30));
        jSpinner1.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel6.setBackground(new java.awt.Color(100, 100, 100));
        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setMaximumSize(new java.awt.Dimension(3343446, 96));
        jLabel6.setMinimumSize(new java.awt.Dimension(36, 26));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(149, 20));

        jXDatePicker1.setBackground(new java.awt.Color(254, 254, 254));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setCornerSize(6);
        dropShadowBorder6.setShadowSize(3);
        dropShadowBorder6.setShowLeftShadow(true);
        jXDatePicker1.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder6, javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0))));
        jXDatePicker1.setMaximumSize(new java.awt.Dimension(111, 30));
        jXDatePicker1.setMinimumSize(new java.awt.Dimension(111, 30));
        jXDatePicker1.setPreferredSize(new java.awt.Dimension(111, 30));
        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setCornerSize(6);
        dropShadowBorder7.setShadowSize(3);
        dropShadowBorder7.setShowLeftShadow(true);
        dropShadowBorder7.setShowTopShadow(true);
        jLabel1.setBorder(dropShadowBorder7);
        jLabel1.setMaximumSize(new java.awt.Dimension(131333, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(131, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(131, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel1.setText(lingua.translate("Início"));
        JSpinner.DefaultEditor spinnerEditor = (JSpinner.DefaultEditor) jSpinner1.getEditor();
        spinnerEditor.getTextField().setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSpinner1.setModel(new SpinnerDateModel());
        jSpinner1.setEditor(new JSpinner.DateEditor(jSpinner1, "HH:mm"));
        javax.swing.JFormattedTextField ff = (javax.swing.JFormattedTextField)((javax.swing.JSpinner.DateEditor)jSpinner1.getEditor()).getComponent(0);
        ff.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabel1.setText(lingua.translate("Início"));
        javax.swing.JPanel pan2 = new javax.swing.JPanel(null);
        String compoe = lingua.translate("Hoje é dia")+": "+new TimeDate.Date().toString();
        javax.swing.JLabel fil2 = new javax.swing.JLabel(compoe);
        fil2.setBounds(0, 0, 300, 26);
        fil2.setHorizontalAlignment(SwingConstants.CENTER);
        pan2.setPreferredSize(new Dimension(300,30));
        pan2.setBounds(0, 0, 300, 30);
        pan2.add(fil2);
        jXDatePicker1.setLinkPanel(pan2);

        jXDatePicker1.setLocale(lingua.systemlocale);
        jXDatePicker1.getEditor().setSelectionColor(Color.DARK_GRAY);
        jXDatePicker1.getEditor().setBorder(BorderFactory.createEmptyBorder());
        jXDatePicker1.getEditor().setHorizontalAlignment(SwingConstants.CENTER);
        javax.swing.JButton bbt2 = (javax.swing.JButton) jXDatePicker1.getComponent(1);
        bbt2.setBackground(Color.WHITE);

        jXDatePicker1.setFormats("dd/MM/yyyy");
        jXDatePicker1.setDate(new java.util.Date());
        jLabel1.setText(lingua.translate("Início da requisição"));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder8 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder8.setCornerSize(6);
        dropShadowBorder8.setShadowSize(3);
        dropShadowBorder8.setShowLeftShadow(true);
        jSpinner2.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder8, javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0))));
        jSpinner2.setMinimumSize(new java.awt.Dimension(50, 30));
        jSpinner2.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel9.setBackground(new java.awt.Color(100, 100, 100));
        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hora");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setMaximumSize(new java.awt.Dimension(3343446, 96));
        jLabel9.setMinimumSize(new java.awt.Dimension(36, 26));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder9 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder9.setCornerSize(6);
        dropShadowBorder9.setShadowSize(3);
        dropShadowBorder9.setShowLeftShadow(true);
        dropShadowBorder9.setShowTopShadow(true);
        jLabel4.setBorder(dropShadowBorder9);
        jLabel4.setMaximumSize(new java.awt.Dimension(131333, 300));
        jLabel4.setMinimumSize(new java.awt.Dimension(131, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(131, 30));

        jLabel10.setBackground(new java.awt.Color(100, 100, 100));
        jLabel10.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setMaximumSize(new java.awt.Dimension(3343446, 96));
        jLabel10.setMinimumSize(new java.awt.Dimension(36, 26));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(149, 20));

        jXDatePicker2.setBackground(new java.awt.Color(254, 254, 254));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder10 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder10.setCornerSize(6);
        dropShadowBorder10.setShadowSize(3);
        dropShadowBorder10.setShowLeftShadow(true);
        jXDatePicker2.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder10, javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0))));
        jXDatePicker2.setMaximumSize(new java.awt.Dimension(111, 30));
        jXDatePicker2.setMinimumSize(new java.awt.Dimension(111, 30));
        jXDatePicker2.setPreferredSize(new java.awt.Dimension(111, 30));
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        JSpinner.DefaultEditor spinnerEditor2 = (JSpinner.DefaultEditor) jSpinner2.getEditor();
        spinnerEditor2.getTextField().setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSpinner2.setModel(new SpinnerDateModel());
        jSpinner2.setEditor(new JSpinner.DateEditor(jSpinner2, "HH:mm"));
        ff = (javax.swing.JFormattedTextField)((javax.swing.JSpinner.DateEditor)jSpinner2.getEditor()).getComponent(0);
        ff.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabel1.setText(lingua.translate("Início"));
        jLabel4.setText(lingua.translate("Fim da requisição"));
        jLabel1.setText(lingua.translate("Início"));
        javax.swing.JPanel pan3 = new javax.swing.JPanel(null);
        pan3.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20), BorderFactory.createMatteBorder(1, 0, 0, 0, Color.BLACK)));
        String compoe2 = lingua.translate("Hoje é dia")+": "+new TimeDate.Date().toString();
        javax.swing.JLabel fil3 = new javax.swing.JLabel(compoe2);
        fil3.setBounds(0, 0, 300, 26);
        fil3.setHorizontalAlignment(SwingConstants.CENTER);
        pan3.setPreferredSize(new Dimension(300,30));
        pan3.setBounds(0, 0, 300, 30);
        pan3.add(fil3);
        jXDatePicker2.setLinkPanel(pan3);

        jXDatePicker2.setLocale(lingua.systemlocale);
        jXDatePicker2.getEditor().setSelectionColor(Color.DARK_GRAY);
        jXDatePicker2.getEditor().setBorder(BorderFactory.createEmptyBorder());
        jXDatePicker2.getEditor().setHorizontalAlignment(SwingConstants.CENTER);
        javax.swing.JButton bbt3 = (javax.swing.JButton) jXDatePicker2.getComponent(1);
        bbt3.setBackground(Color.WHITE);

        jXDatePicker2.setFormats("dd/MM/yyyy");
        jXDatePicker2.setDate(new java.util.Date());

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        jPanelInicial.setBackground(corfundo);
        jPanelInicial.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(corborda, 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaterialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jComboBoxNomeUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomeUtilizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomeUtilizadorActionPerformed

    private void jComboBoxCodigoUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCodigoUtilizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCodigoUtilizadorActionPerformed

    private void init() {
        this.setTitle(lingua.translate("Registo de requisição"));
        this.setBackground(corfundo);

    }

    private void close() {
        prefs.putInt("largura", this.getWidth());
        prefs.putInt("altura", this.getHeight());
        prefs.putInt("x", getX());
        prefs.putInt("y", getY());
        prefs.putInt("maximizada", this.getExtendedState());
        this.setVisible(false);
        this.dispose();
    }

    public void appear() {
        this.setVisible(true);
        int largura = prefs.getInt("largura", (int) this.getPreferredSize().getWidth());
        int altura = prefs.getInt("altura", (int) this.getPreferredSize().getHeight());
        int x = prefs.getInt("x", this.getX());
        int y = prefs.getInt("y", this.getY());
        int max = prefs.getInt("maximizada", this.getExtendedState());
        this.setExtendedState(max);
        this.setBounds(x, y, largura, altura);
        this.setVisible(true);
    }

    public void create() {
        initComponents();
        init();
        jLabelRecurso.requestFocus();
        spineditor = (javax.swing.JSpinner.NumberEditor) jSpinnerQuantidade.getEditor();
        spineditor.getFormat().setGroupingUsed(false);
        spineditor.getModel().setMinimum(1);
        spineditor.getModel().setValue(1);
        spineditor.getModel().setStepSize(1);
        spineditor.getTextField().setSelectionColor(Color.DARK_GRAY);
        javax.swing.JTextField tx = (javax.swing.JTextField) jComboBoxTipoMaterial.getEditor().getEditorComponent();
        tx.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 8));
        javax.swing.JTextField txm = (javax.swing.JTextField) jComboBoxMaterial.getEditor().getEditorComponent();
        txm.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 8));
        javax.swing.JTextField txmutilizador = (javax.swing.JTextField) jComboBoxNomeUtilizador.getEditor().getEditorComponent();
        txmutilizador.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 8));
        javax.swing.JTextField txmcodigo = (javax.swing.JTextField) jComboBoxCodigoUtilizador.getEditor().getEditorComponent();
        txmcodigo.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 8));
        txm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txmcodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txmutilizador.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        javax.swing.JSpinner.DefaultEditor editor = (javax.swing.JSpinner.DefaultEditor) jSpinnerQuantidade.getEditor();
        javax.swing.JTextField txx = editor.getTextField();
        txx.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if ((int) jSpinnerQuantidade.getValue() > 1) {
                    jComboBoxMaterial.setSelectedIndex(0);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if ((int) jSpinnerQuantidade.getValue() > 1) {
                    jComboBoxMaterial.setSelectedIndex(0);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if ((int) jSpinnerQuantidade.getValue() > 1) {
                    jComboBoxMaterial.setSelectedIndex(0);
                }
            }
        });
        jSpinnerQuantidade.addChangeListener((ChangeEvent e) -> {
            if ((int) jSpinnerQuantidade.getValue() > 0) {
                //    jComboBoxMaterial.setSelectedIndex(0);
            }
        });
        entrou = false;
        jComboBoxTipoMaterial.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBoxTipoMaterial.getSelectedIndex() > 0) {
                    spineditor.getModel().setValue(1);
                    DataBase.DataBase db = new DataBase.DataBase(url);
                    int val = db.getNumberOfFreeMaterials(tlista.get(jComboBoxTipoMaterial.getSelectedIndex() - 1));
                    spineditor.getModel().setMaximum(val);
                    mlista = db.getMaterialsByType(tlista.get(jComboBoxTipoMaterial.getSelectedIndex() - 1).getMaterialTypeID(), 0);
                    DefaultComboBoxModel<Keys.Material> modelo = (DefaultComboBoxModel) jComboBoxMaterial.getModel();
                    jComboBoxMaterial.removeAllItems();
                    int i = 0;
                    int valor = 0;
                    for (Keys.Material n : mlista) {
                        String nome = lingua.translate(n.getDescription());
                        if (n.getMaterialTypeID() == 1) {
                            n.setDescription(lingua.translate("Sala de aula").toLowerCase() + " " + lingua.translate(n.getDescription()));
                        } else {
                            n.setDescription(lingua.translate(n.getDescription()));
                        }
                        modelo.addElement(n);
                        if ((mat != null) && (n.getId() == mat.getId()) && (!entrou)) {
                            valor = i;
                            entrou = true;
                        }
                        i++;
                    }
                    jComboBoxMaterial.setSelectedIndex(valor);

                } else {
                    jComboBoxMaterial.removeAllItems();
                    jComboBoxMaterial.setSelectedIndex(0);
                    spineditor.getModel().setMaximum(1);
                    jSpinnerQuantidade.setValue(1);
                }
            }
        });
        jComboBoxMaterial.addActionListener((ActionEvent e) -> {
            if (jComboBoxMaterial.getSelectedIndex() > 0) {
                jSpinnerQuantidade.setValue(1);
            }
        });
        if (DataBase.DataBase.testConnection(url)) {
            DefaultComboBoxModel<Keys.TypeOfMaterial> modelo = (DefaultComboBoxModel) jComboBoxTipoMaterial.getModel();
            DefaultComboBoxModel<Keys.Material> modelo2 = (DefaultComboBoxModel) jComboBoxMaterial.getModel();
            DataBase.DataBase db = new DataBase.DataBase(url);
            tlista = db.getTypesOfMaterial();
            for (int h = 0; h < tlista.size(); h++) {
                if (tlista.get(h).getMaterialTypeID() == 1) {
                    Keys.TypeOfMaterial m = tlista.get(0);
                    tlista.set(0, tlista.get(h));
                    tlista.set(h, m);
                }
            }
            if (tlista.size() > 0) {
                int i = 0;
                for (Keys.TypeOfMaterial m : tlista) {
                    m.setTypeOfMaterialName(lingua.translateWithPlural(m.getTypeOfMaterialName()));
                    modelo.addElement(m);
                    if (mat != null) {
                        if (m.getMaterialTypeID() == mat.getMaterialTypeID()) {
                            jComboBoxTipoMaterial.setSelectedIndex(i + 1);
                        }
                    }
                    i++;
                }
                if (jComboBoxTipoMaterial.getSelectedIndex() < 1) {
                    jComboBoxTipoMaterial.setSelectedIndex(0);
                }
            }
            java.util.List<Keys.Person> p = db.getPersons();
            DefaultComboBoxModel<Keys.Person> modelop = (DefaultComboBoxModel) jComboBoxNomeUtilizador.getModel();
            p.stream().forEach((pes) -> {
                modelop.addElement(pes);
            });
            jComboBoxNomeUtilizador.setSelectedIndex(0);
            db.close();
            
            
        }
        
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapterImpl());
        pack();
    }

    public static final void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                WRequest wr = new WRequest();
                wr.create();
                wr.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    /*
    private javax.swing.JComboBox<String> jComboBoxCodigoUtilizador;
    */
    private Components.PersonalComboBox jComboBoxCodigoUtilizador;
    /*
    private javax.swing.JComboBox<String> jComboBoxMaterial;
    */
    private Components.PersonalComboBox jComboBoxMaterial;
    /*
    private javax.swing.JComboBox<String> jComboBoxNomeUtilizador;
    */
    private Components.PersonalComboBox jComboBoxNomeUtilizador;
    /*
    private javax.swing.JComboBox<String> jComboBoxTipoMaterial;
    */
    private Components.PersonalComboBox jComboBoxTipoMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPessoa;
    private javax.swing.JLabel jLabelRecurso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinnerQuantidade;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tlista
     */
    public java.util.List<Keys.TypeOfMaterial> getTypeMaterialList() {
        return tlista;
    }

    /**
     * @param tlista the tlista to set
     */
    public void setTypeMaterialList(java.util.List<Keys.TypeOfMaterial> tlista) {
        this.tlista = tlista;
    }

    private class WindowAdapterImpl extends WindowAdapter {

        public WindowAdapterImpl() {
        }

        @Override
        public void windowClosing(WindowEvent e) {
            close();
        }
    }
}
