/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clavis.Windows;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author toze
 */
public class WResources extends javax.swing.JFrame {
    
    private Color corborda;
    private Color corfundo;
    private String url;
    private Langs.Locale lingua;
    private List<Keys.TypeOfMaterial> tiposdematerial;
    private Keys.TypeOfMaterial tiposelecionado;
    
    public WResources(Color corfundo, Color corborda, String url, Langs.Locale lingua) {
        this.corborda = corborda;
        this.corfundo = corfundo;
        this.url = url;
        this.lingua = lingua;
        tiposelecionado = null;
        tiposdematerial = new java.util.ArrayList<>();
    }
    
    public void makePanel(){
        Border b = BorderFactory.createLineBorder(corborda, 4);
        jPanelInicial.setBorder(BorderFactory.createCompoundBorder(b, BorderFactory.createLineBorder(Color.BLACK)));
        jPanelInicial.setBackground(corfundo);
        Dimension s = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int)(s.getWidth()/2 - this.getWidth()/2), (int)(s.getHeight()/2-this.getHeight()/2));
    }
    
    public void appear(){
        this.setVisible(true);
    }
    
    public void makeTypeMaterialList(){
        if (DataBase.DataBase.testConnection(url)) {
            DataBase.DataBase db = new DataBase.DataBase(url);
            tiposdematerial = db.getTypesOfMaterial();
            DefaultListModel<Keys.TypeOfMaterial> modelo = new DefaultListModel<>();
            tiposdematerial.stream().forEach((tipo) -> {
                tipo = new Keys.TypeOfMaterial(tipo) {
                    @Override
                    public String toString(){
                        return lingua.translateWithPlural(this.getTypeOfMaterialName());
                    }
                };
                modelo.addElement(tipo);
            });
            jListTipoMaterial.setModel(modelo);
            db.close();
        }
    }
    
    
    public void create(){
        initComponents();
        makePanel();
        makeTypeMaterialList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jLabelTipoMaterial = new javax.swing.JLabel();
        jScrollPaneTipoMaterial = new javax.swing.JScrollPane();
        jListTipoMaterial = new javax.swing.JList<>();
        jTextFieldTipoMaterial = new Components.PersonalTextField();
        jToogleBlock = new Components.PersonalToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanelInicial.setBackground(new java.awt.Color(254, 254, 254));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelInicial.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabelTipoMaterial.setBackground(new java.awt.Color(250, 250, 250));
        jLabelTipoMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTipoMaterial.setOpaque(true);

        jListTipoMaterial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneTipoMaterial.setViewportView(jListTipoMaterial);
        jListTipoMaterial.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jListTipoMaterial.setCellRenderer(new DefaultListCellRenderer() {
            private static final long serialVersionUID = 2L;

            @Override
            public Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                javax.swing.JLabel label = (javax.swing.JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                label.setPreferredSize(new Dimension(150, 30));
                if (isSelected) {
                    label.setBackground(Color.GRAY);
                    label.setForeground(Color.WHITE);
                    label.setBorder(BorderFactory.createLineBorder(Color.black, 1));
                }
                return label;
            }
        });
        jListTipoMaterial.setPreferredSize(new Dimension(220, 130));
        jListTipoMaterial.setBackground(new Color(250, 250, 250));

        jScrollPaneTipoMaterial.setBorder(BorderFactory.createCompoundBorder(new org.jdesktop.swingx.border.DropShadowBorder(Color.BLACK, 3, 0.5f, 6, false, true, true, true), BorderFactory.createLineBorder(Color.BLACK)));
        jScrollPaneTipoMaterial.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jToogleBlock.setMaximumSize(new java.awt.Dimension(34, 34));
        jToogleBlock.setMinimumSize(new java.awt.Dimension(34, 34));
        jToogleBlock.setPreferredSize(new java.awt.Dimension(34, 34));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addComponent(jToogleBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(520, Short.MAX_VALUE))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToogleBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jLabelTipoMaterial.setText(lingua.translate("Tipos de Material"));
        jTextFieldTipoMaterial.addPlaceHolder(lingua.translate("Escrever novo tipo de material"), jLabelTipoMaterial);
        Border f = BorderFactory.createCompoundBorder(new org.jdesktop.swingx.border.DropShadowBorder(Color.BLACK, 3, 0.5f, 6, false, false, true, true), BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldTipoMaterial.setBorder(BorderFactory.createCompoundBorder(f, BorderFactory.createEmptyBorder(0, 10, 0, 10)));
        jTextFieldTipoMaterial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        try {
            if (Clavis.KeyQuest.class.getResource("Images/lock.png") != null) {
                BufferedImage im = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/lock.png"));
                ImageIcon imo = new ImageIcon(im);
                jToogleBlock.setIcon(imo);
            } else {
                jToogleBlock.setText("X");
            }
        } catch (IOException ex){}

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WResources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            WResources wr = new WResources(new Color(125,234,145),new Color(255,255,255),"",Langs.Locale.getLocale_pt_PT());
            wr.create();
            wr.appear();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTipoMaterial;
    /*
    private javax.swing.JList<String> jListTipoMaterial;
    */

    private javax.swing.JList<Keys.TypeOfMaterial> jListTipoMaterial;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JScrollPane jScrollPaneTipoMaterial;
    private Components.PersonalTextField jTextFieldTipoMaterial;
    private Components.PersonalToggleButton jToogleBlock;
    // End of variables declaration//GEN-END:variables
}
