/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clavis.Windows;

import java.awt.Color;
import Components.*;
import Langs.Locale;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicComboPopup;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author toze
 */
public class WUsers extends javax.swing.JFrame {

    private Color corfundo;
    private Color corborda;
    private String url;
    private Locale lingua;
    private boolean superuser;
    private java.util.List<Keys.Function> lfuncoes;
    private java.util.List<Keys.Person> lpessoas;
    private Keys.Person selecionado;
    private javax.swing.JFrame frame;

    public WUsers(Color corfundo, Color corborda, String url, Locale lingua, boolean superuser, javax.swing.JFrame frame) {
        this.corborda = corborda;
        this.corfundo = corfundo;
        this.lingua = lingua;
        this.url = url;
        this.superuser = superuser;
        this.lfuncoes = new java.util.ArrayList<>();
        this.lpessoas = new java.util.ArrayList<>();
        this.selecionado = null;
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAdicionarNome = new javax.swing.JLabel();
        jLabelAdicionarEmail = new javax.swing.JLabel();
        jLabelAdicionarTelefone = new javax.swing.JLabel();
        jLabelAdicionarFuncao = new javax.swing.JLabel();
        txAdicionarNome = new Components.PersonalTextField();
        txAdicionarEmail = new Components.PersonalTextField();
        txAdicionarTelefone = new Components.PersonalTextField();
        jComboBoxAdicionarFuncao = new javax.swing.JComboBox<>();
        jLabelAdicionarIdentificacao = new javax.swing.JLabel();
        txAdicionarIdentificacao = new Components.PersonalTextField();
        jLabelAdicionarPrivilegio = new javax.swing.JLabel();
        jSpinnerAdicionarPrivilegio = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneUtilizadores = new javax.swing.JScrollPane();
        jTableUtilizadores = new org.jdesktop.swingx.JXTable();
        jButtonExit = new javax.swing.JButton();
        jLabelTituloAdicionar = new javax.swing.JLabel();
        jLabelEditar = new javax.swing.JLabel();
        jButtonAdicionarGuardar = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        jButtonPesquisa = new javax.swing.JButton();
        txPesquisa = new Components.PersonalTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        jPanelInicial.setBackground(new java.awt.Color(254, 254, 254));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanelInicial.setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setBackground(new java.awt.Color(249, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new org.jdesktop.swingx.border.DropShadowBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel1.setMinimumSize(new java.awt.Dimension(420, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 440));

        jLabelAdicionarNome.setText("Nome:");
        jLabelAdicionarNome.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarNome.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarNome.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabelAdicionarEmail.setText("E-mail:");
        jLabelAdicionarEmail.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarEmail.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarEmail.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabelAdicionarTelefone.setText("Telefone:");
        jLabelAdicionarTelefone.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarTelefone.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarTelefone.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabelAdicionarFuncao.setText("Função:");
        jLabelAdicionarFuncao.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarFuncao.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarFuncao.setPreferredSize(new java.awt.Dimension(120, 30));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setCornerSize(6);
        dropShadowBorder1.setShadowSize(2);
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        txAdicionarNome.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder1, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10))));
        txAdicionarNome.setMaximumSize(new java.awt.Dimension(254, 30));
        txAdicionarNome.setMinimumSize(new java.awt.Dimension(254, 30));
        txAdicionarNome.setPreferredSize(new java.awt.Dimension(254, 30));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setCornerSize(6);
        dropShadowBorder2.setShadowSize(2);
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        txAdicionarEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder2, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10))));
        txAdicionarEmail.setMaximumSize(new java.awt.Dimension(254, 30));
        txAdicionarEmail.setMinimumSize(new java.awt.Dimension(254, 30));
        txAdicionarEmail.setPreferredSize(new java.awt.Dimension(254, 30));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setCornerSize(6);
        dropShadowBorder3.setShadowSize(2);
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        txAdicionarTelefone.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder3, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10))));
        txAdicionarTelefone.setMaximumSize(new java.awt.Dimension(254, 30));
        txAdicionarTelefone.setMinimumSize(new java.awt.Dimension(254, 30));
        txAdicionarTelefone.setPreferredSize(new java.awt.Dimension(254, 30));

        jComboBoxAdicionarFuncao.setBackground(new java.awt.Color(253, 253, 253));
        jComboBoxAdicionarFuncao.setFocusable(false);
        jComboBoxAdicionarFuncao.setMaximumSize(new java.awt.Dimension(254, 30));
        jComboBoxAdicionarFuncao.setMinimumSize(new java.awt.Dimension(254, 30));
        jComboBoxAdicionarFuncao.setPreferredSize(new java.awt.Dimension(254, 30));

        jLabelAdicionarIdentificacao.setText("Identificação:");
        jLabelAdicionarIdentificacao.setToolTipText("");
        jLabelAdicionarIdentificacao.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarIdentificacao.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarIdentificacao.setPreferredSize(new java.awt.Dimension(120, 30));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setCornerSize(6);
        dropShadowBorder4.setShadowSize(2);
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        txAdicionarIdentificacao.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder4, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10))));
        txAdicionarIdentificacao.setEnabled(false);
        txAdicionarIdentificacao.setMaximumSize(new java.awt.Dimension(254, 30));
        txAdicionarIdentificacao.setMinimumSize(new java.awt.Dimension(254, 30));
        txAdicionarIdentificacao.setPreferredSize(new java.awt.Dimension(254, 30));
        txAdicionarIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAdicionarIdentificacaoActionPerformed(evt);
            }
        });

        jLabelAdicionarPrivilegio.setText("Privilégio:");
        jLabelAdicionarPrivilegio.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarPrivilegio.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabelAdicionarPrivilegio.setPreferredSize(new java.awt.Dimension(120, 30));

        jSpinnerAdicionarPrivilegio.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSpinnerAdicionarPrivilegio.setMinimumSize(new java.awt.Dimension(100, 30));
        jSpinnerAdicionarPrivilegio.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelAdicionarIdentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAdicionarTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAdicionarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAdicionarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAdicionarFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelAdicionarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerAdicionarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAdicionarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txAdicionarIdentificacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxAdicionarFuncao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txAdicionarTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txAdicionarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAdicionarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txAdicionarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdicionarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAdicionarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdicionarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAdicionarFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxAdicionarFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdicionarIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAdicionarIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdicionarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAdicionarPrivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelAdicionarNome.setText(lingua.translate("Nome")+":");
        jLabelAdicionarEmail.setText(lingua.translate("E-mail")+":");
        jLabelAdicionarTelefone.setText(lingua.translate("Telefone")+":");
        jLabelAdicionarFuncao.setText(lingua.translate("Função")+":");
        txAdicionarNome.addPlaceHolder(lingua.translate("Nome de utilizador")+" ...", jLabelAdicionarNome);
        txAdicionarEmail.addPlaceHolder(lingua.translate("Correio eletrónico")+" ...", jLabelAdicionarNome);
        txAdicionarTelefone.addPlaceHolder(lingua.translate("Telefone ou telemóvel")+" ...", jLabelAdicionarNome);
        Components.PersonalCombo.setHorizontalTextPosition(javax.swing.JTextField.CENTER, jComboBoxAdicionarFuncao);
        ((javax.swing.JLabel)jComboBoxAdicionarFuncao.getRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);

        BasicComboPopup popupVista = (BasicComboPopup) jComboBoxAdicionarFuncao.getAccessibleContext().getAccessibleChild(0);
        popupVista.getList().setSelectionBackground(Color.DARK_GRAY);
        popupVista.getList().setBorder(BorderFactory.createEmptyBorder(1, 2, 1, 2));
        jLabelAdicionarIdentificacao.setText(lingua.translate("Identificação")+":");
        txAdicionarIdentificacao.addPlaceHolder(lingua.translate("Identificação na instituição")+" ...", jLabelAdicionarNome);
        if (superuser) {
            jLabelAdicionarPrivilegio.setVisible(true);
        } else {
            jLabelAdicionarPrivilegio.setVisible(false);
        }
        jLabelAdicionarPrivilegio.setText(lingua.translate("Privilégio")+":");
        if (superuser) {
            jSpinnerAdicionarPrivilegio.setVisible(true);
        } else {
            jSpinnerAdicionarPrivilegio.setVisible(false);
        }

        jPanel2.setBackground(new java.awt.Color(146, 155, 216));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 440));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 440));

        jTableUtilizadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneUtilizadores.setViewportView(jTableUtilizadores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneUtilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneUtilizadores)
        );

        jButtonExit.setBackground(new java.awt.Color(1, 1, 1));
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.setFocusPainted(false);
        jButtonExit.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonExit.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonExit.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelTituloAdicionar.setBackground(new java.awt.Color(250, 250, 250));
        jLabelTituloAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTituloAdicionar.setMaximumSize(new java.awt.Dimension(222222220, 222220));
        jLabelTituloAdicionar.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabelTituloAdicionar.setOpaque(true);
        jLabelTituloAdicionar.setPreferredSize(new java.awt.Dimension(420, 30));

        jLabelEditar.setBackground(new java.awt.Color(250, 250, 250));
        jLabelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelEditar.setMaximumSize(new java.awt.Dimension(36222222, 12222222));
        jLabelEditar.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabelEditar.setOpaque(true);
        jLabelEditar.setPreferredSize(new java.awt.Dimension(420, 30));

        jButtonAdicionarGuardar.setBackground(new java.awt.Color(51, 102, 153));
        jButtonAdicionarGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarGuardar.setFocusPainted(false);
        jButtonAdicionarGuardar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonAdicionarGuardar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonAdicionarGuardar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAdicionarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarGuardarActionPerformed(evt);
            }
        });

        jButtonReiniciar.setBackground(new java.awt.Color(253, 67, 67));
        jButtonReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReiniciar.setFocusPainted(false);
        jButtonReiniciar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonReiniciar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonReiniciar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jButtonPesquisa.setBackground(new java.awt.Color(51, 102, 153));
        jButtonPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisa.setFocusPainted(false);
        jButtonPesquisa.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonPesquisa.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonPesquisa.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setCornerSize(6);
        dropShadowBorder5.setShadowSize(2);
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        txPesquisa.setBorder(javax.swing.BorderFactory.createCompoundBorder(dropShadowBorder5, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10))));
        txPesquisa.setMaximumSize(new java.awt.Dimension(315, 30));
        txPesquisa.setMinimumSize(new java.awt.Dimension(315, 30));
        txPesquisa.setPreferredSize(new java.awt.Dimension(315, 30));

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInicialLayout.createSequentialGroup()
                                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAdicionarGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTituloAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        try {
            if (Clavis.KeyQuest.class.getResource("Images/exit26x24.png") != null) {
                BufferedImage bfexit = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/exit26x24.png"));
                ImageIcon imexit = new ImageIcon(bfexit);
                jButtonExit.setIcon(imexit);
            } else {
                jButtonExit.setText(lingua.translate("Voltar"));
            }

        } catch (IOException e) {}
        jButtonExit.setToolTipText(lingua.translate("Voltar"));
        if (selecionado == null) {
            jLabelTituloAdicionar.setText(lingua.translate("Adicionar utilizador"));
        } else {
            jLabelTituloAdicionar.setText(lingua.translate("Editar utilizador"));
        }
        jLabelEditar.setText(lingua.translate("Lista de utilizadores"));
        if (selecionado == null) {
            try {
                if (Clavis.KeyQuest.class.getResource("Images/save.png") != null) {
                    BufferedImage bfsave = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/save.png"));
                    ImageIcon imsave = new ImageIcon(bfsave);
                    jButtonAdicionarGuardar.setIcon(imsave);
                } else {
                    jButtonAdicionarGuardar.setText(lingua.translate("Guardar"));
                }
            } catch (IOException e) {}
        } else {
            try {
                if (Clavis.KeyQuest.class.getResource("Images/ok.png") != null) {
                    BufferedImage bfsave = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/ok.png"));
                    ImageIcon imsave = new ImageIcon(bfsave);
                    jButtonAdicionarGuardar.setIcon(imsave);
                } else {
                    jButtonAdicionarGuardar.setText(lingua.translate("Editar"));
                }
            } catch (IOException e) {}
        }
        if (selecionado == null) {
            jButtonAdicionarGuardar.setToolTipText(lingua.translate("Registar novo utilizador")+".");
        } else {
            jButtonAdicionarGuardar.setToolTipText(lingua.translate("Guardar novos valores")+".");
        }
        if (selecionado != null) {
            jButtonReiniciar.setVisible(true);
        } else {
            jButtonReiniciar.setVisible(false);
        }
        try {
            if (Clavis.KeyQuest.class.getResource("Images/limpar.png") != null) {
                BufferedImage bfexit = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/limpar.png"));
                ImageIcon imexit = new ImageIcon(bfexit);
                jButtonReiniciar.setIcon(imexit);
            } else {
                jButtonReiniciar.setText(lingua.translate("Limpar"));
            }

        } catch (IOException e) {}
        jButtonReiniciar.setToolTipText(lingua.translate("Limpar seleção"));
        try {
            if (Clavis.KeyQuest.class.getResource("Images/lupa.png") != null) {
                BufferedImage bfexit = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/lupa.png"));
                ImageIcon imexit = new ImageIcon(bfexit);
                jButtonPesquisa.setIcon(imexit);
            } else {
                jButtonPesquisa.setText(lingua.translate("Pesquisar"));
            }

        } catch (IOException e) {}
        jButtonExit.setToolTipText(lingua.translate("Pesquisar por utilizador"));
        txPesquisa.addPlaceHolder(lingua.translate("Caixa de pesquisa")+" ...", jLabelAdicionarNome);

        txPesquisa.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(5, 0, 5, 0, jPanelInicial.getBackground()), txPesquisa.getBorder()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        jPanelInicial.setBackground(corfundo);
        jPanelInicial.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(corborda, 4), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.close();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        this.clearSelection();
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        String pesquisa = txPesquisa.getText();
        if (!pesquisa.equals("")) {
            Keys.Person sel = null;
            int i = 0;
            for (Keys.Person p : lpessoas) {
                if (pesquisa.equals(p.getIdentification()) || (pesquisa.equals(p.getEmail()))) {
                    sel = p;
                    break;
                }
                String mov = pesquisa;
                String mov2 = p.getName();
                mov = mov.replaceAll("[áàãäâ]", "a");
                mov = mov.replaceAll("[íìîĩï]", "i");
                mov = mov.replaceAll("[éèêẽë]", "e");
                mov = mov.replaceAll("[úùũüû]", "u");
                mov = mov.replaceAll("[óòôõö]", "o");
                mov = mov.replaceAll("[ñ]", "n");
                mov2 = mov2.replaceAll("[áàãäâ]", "a");
                mov2 = mov2.replaceAll("[íìîĩï]", "i");
                mov2 = mov2.replaceAll("[éèêẽë]", "e");
                mov2 = mov2.replaceAll("[úùũüû]", "u");
                mov2 = mov2.replaceAll("[óòôõö]", "o");
                mov2 = mov2.replaceAll("[ñ]", "n");
                if ((mov2.toLowerCase().matches("(.*)" + mov.toLowerCase().replaceAll("[\\[\\]\\(\\)\\/\\{\\}\"\\#$%&=\\\\]+", "") + "(.*)"))) {
                    sel = p;
                    break;
                }
                i++;
            } if (sel != null) {
                jTableUtilizadores.setRowSelectionInterval(i, i);
                this.select(i);
            } 
        }
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void txAdicionarIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAdicionarIdentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAdicionarIdentificacaoActionPerformed

    private void jButtonAdicionarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarGuardarActionPerformed

    public void create() {
        this.setTitle(lingua.translate("Registo de utilizador"));
        if (frame != null) {
            this.setAlwaysOnTop(true);
        }
        this.setBackground(corfundo);
        initComponents();
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                close();
            }
        });

        // combobox das funções 
        DefaultComboBoxModel<Keys.Function> modelo = (DefaultComboBoxModel) jComboBoxAdicionarFuncao.getModel();
        if (DataBase.DataBase.testConnection(url)) {
            DataBase.DataBase db = new DataBase.DataBase(url);
            java.util.List<Keys.Function> lista = db.getFunctions();
            lfuncoes = new java.util.ArrayList<>(lista);
            db.close();
            for (int i = 0; i < lista.size(); i++) {
                lista.get(i).setName(lingua.translate(lista.get(i).getName()));
                modelo.addElement(lista.get(i));
            }
        }
        jComboBoxAdicionarFuncao.addActionListener((ActionEvent e) -> {
            if ((jComboBoxAdicionarFuncao.getItemCount() > 0) && (jComboBoxAdicionarFuncao.getSelectedIndex() > 0)) {
                txAdicionarIdentificacao.setEnabled(true);
            } else {
                txAdicionarIdentificacao.setText("");
                txAdicionarIdentificacao.showPLaceHolder();
                txAdicionarIdentificacao.setEnabled(false);
            }
        });

        // tabela
        makeTable();
        txPesquisa.addActionListener((ActionEvent e)-> {
            jButtonPesquisa.doClick();
        });
        jLabelAdicionarNome.requestFocus();
        txAdicionarNome.addMouseListener( Components.PopUpMenu.simpleCopyPaste(lingua, txAdicionarNome, false));
        txAdicionarEmail.addMouseListener( Components.PopUpMenu.simpleCopyPaste(lingua, txAdicionarEmail, false));
        txAdicionarTelefone.addMouseListener( Components.PopUpMenu.simpleCopyPaste(lingua, txAdicionarTelefone, false));
        txAdicionarIdentificacao.addMouseListener( Components.PopUpMenu.simpleCopyPaste(lingua, txAdicionarIdentificacao, false));
        txPesquisa.addMouseListener( Components.PopUpMenu.simpleCopyPaste(lingua, txPesquisa, false));
    }

    private void close() {
        this.setVisible(false);
        this.dispose();
        if (frame != null) {
            frame.setLocation(this.getX(), this.getY());
            frame.setVisible(true);
        }
    }

    public void makeTable() {
        jTableUtilizadores.setBorder(null);
        javax.swing.table.DefaultTableModel model;
        if (DataBase.DataBase.testConnection(url)) {
            DataBase.DataBase db = new DataBase.DataBase(url);
            lpessoas = db.getPersons();
            if (lpessoas.isEmpty()) {
                model = new javax.swing.table.DefaultTableModel(new Object[][]{}, new Object[]{lingua.translate("Situação")});
                model.addRow(new Object[]{lingua.translate("Lista vazia")});
            } else {
                model = new javax.swing.table.DefaultTableModel(new Object[][]{}, new Object[]{lingua.translate("Nome"), lingua.translate("Contato telefónico")});
                for (Keys.Person p : lpessoas) {
                    Object[] objetos = {p.getName(), p.getPhone()};
                    model.addRow(objetos);
                }
            }
        } else {
            model = new javax.swing.table.DefaultTableModel(new Object[][]{}, new Object[]{lingua.translate("Situação")});
            model.addRow(new Object[]{lingua.translate("Problema na ligação à base de dados") + "!"});
        }
        jTableUtilizadores.setModel(model);
        jTableUtilizadores.getColumnModel().getColumn(0).setMinWidth(200);
        jTableUtilizadores.getColumnModel().getColumn(0).setPreferredWidth(220);
        if (jTableUtilizadores.getColumnCount() > 1) {
            jTableUtilizadores.getColumnModel().getColumn(1).setMinWidth(140);
        }
        Border border = BorderFactory.createEmptyBorder(5, 5, 0, 0);
        UIManager.put("Table.focusCellHighlightBorder", border);
        jTableUtilizadores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneUtilizadores.setBackground(Color.WHITE);
        jScrollPaneUtilizadores.setOpaque(true);
        jScrollPaneUtilizadores.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPaneUtilizadores.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneUtilizadores.setBorder(BorderFactory.createCompoundBorder(new org.jdesktop.swingx.border.DropShadowBorder(Color.BLACK, 3, 0.5f, 6, false, true, true, false), BorderFactory.createLineBorder(Color.black, 1)));
        javax.swing.JLabel lo = new javax.swing.JLabel();
        lo.setBackground(new Color(100, 100, 100));
        lo.setOpaque(true);
        jScrollPaneUtilizadores.setCorner(javax.swing.JScrollPane.UPPER_TRAILING_CORNER, lo);
        jTableUtilizadores.setRowHeight(30);
        jTableUtilizadores.setEditable(false);
        jTableUtilizadores.setSelectionBackground(Color.DARK_GRAY);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        DefaultTableCellRenderer renderer2 = new DefaultTableCellRenderer();
        if (jTableUtilizadores.getColumnCount() > 1) {
            renderer2.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        } else {
            renderer2.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        }
        renderer.setFocusable(false);
        jTableUtilizadores.getColumnModel().getColumn(0).setCellRenderer(renderer2);
        if (jTableUtilizadores.getColumnCount() > 1) {
            jTableUtilizadores.getColumnModel().getColumn(1).setCellRenderer(renderer);
        }
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            private static final long serialVersionUID = 2L;

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setFont(new Font("Cantarell", Font.PLAIN, 14));
                this.setBorder(BorderFactory.createMatteBorder(0, 1, 1, 0, new Color(1, 1, 1)));
                return this;
            }
        };
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer() {
            private static final long serialVersionUID = 3L;

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setFont(new Font("Cantarell", Font.PLAIN, 14));
                this.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(1, 1, 1)), BorderFactory.createEmptyBorder(0, 20, 0, 0)));
                this.setBackground(new Color(100, 100, 100));
                setForeground(Color.WHITE);
                setPreferredSize(new Dimension(100, 40));
                return this;
            }
        };
        headerRenderer.setBackground(new Color(100, 100, 100));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setPreferredSize(new Dimension(100, 40));
        headerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        headerRenderer2.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        jTableUtilizadores.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer2);
        if (jTableUtilizadores.getColumnCount() > 1) {
            jTableUtilizadores.getColumnModel().getColumn(1).setHeaderRenderer(headerRenderer);
        }

        jTableUtilizadores.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                java.awt.Point ponto = e.getPoint();
                int sel = jTableUtilizadores.rowAtPoint(ponto);
                if ((sel == jTableUtilizadores.getSelectedRow()) && (sel >= 0)) {
                    select(sel);
                }
            }
        });

        jTableUtilizadores.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    clearSelection();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                int sel = jTableUtilizadores.getSelectedRow();
                if (sel >= 0) {
                    select(sel);
                }
            }
        });
    }

    private void select(int sel) {
        if (lpessoas.size() > 0) {
            Keys.Person p = lpessoas.get(sel);
            selecionado = p;
            txAdicionarNome.stopPlaceHolder();
            txAdicionarNome.setText(p.getName());
            txAdicionarNome.setCaretPosition(0);
            txAdicionarNome.startPlaceHolder();
            if (p.getEmail().equals("sem")) {
                txAdicionarEmail.showWithCondition(lingua.translate("Não existe um email associado") + "!", selecionado != null);
            } else {
                txAdicionarEmail.stopPlaceHolder();
                txAdicionarEmail.setText(p.getEmail());
                txAdicionarNome.setCaretPosition(0);
                txAdicionarEmail.startPlaceHolder();
            }
            if (p.getPhone().equals("sem")) {
                txAdicionarTelefone.showWithCondition(lingua.translate("Não existe nenhum registo") + "!", selecionado != null);
            } else {
                txAdicionarTelefone.stopPlaceHolder();
                txAdicionarTelefone.setText(p.getPhone());
                txAdicionarNome.setCaretPosition(0);
                txAdicionarTelefone.startPlaceHolder();
            }
            if (p.getIdentification().equals("sem")) {
                txAdicionarIdentificacao.showWithCondition(lingua.translate("Não existe código ou identificação") + "!", selecionado != null);
            } else {
                txAdicionarIdentificacao.stopPlaceHolder();
                txAdicionarIdentificacao.setText(p.getPhone());
                txAdicionarNome.setCaretPosition(0);
                txAdicionarIdentificacao.startPlaceHolder();
            }
            jSpinnerAdicionarPrivilegio.setValue(p.getPrivilege());
            for (int j = 0; j < lfuncoes.size(); j++) {
                Keys.Function fo = lfuncoes.get(j);
                if (fo.compareTo(p.getFunction()) == 0) {
                    jComboBoxAdicionarFuncao.setSelectedIndex(j);
                    break;
                }
            }
            if (!p.getIdentification().equals("")) {
                txAdicionarIdentificacao.setText(p.getIdentification());
                txAdicionarNome.setCaretPosition(0);
            }
            jButtonReiniciar.setVisible(true);
        }
        try {
            if (Clavis.KeyQuest.class.getResource("Images/ok.png") != null) {
                BufferedImage bfsave = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/ok.png"));
                ImageIcon imsave = new ImageIcon(bfsave);
                jButtonAdicionarGuardar.setIcon(imsave);
            } else {
                jButtonAdicionarGuardar.setText(lingua.translate("Editar"));
            }
        } catch (IOException e) {
        }
        jButtonAdicionarGuardar.setToolTipText(lingua.translate("Guardar novos valores") + ".");
        jLabelTituloAdicionar.setText(lingua.translate("Editar valores de utilizador"));
        jLabelAdicionarNome.requestFocus();

    }

    private void clearSelection() {
        if (lpessoas.size() > 0) {
            txAdicionarNome.setText("");
            txAdicionarNome.showPLaceHolder();
            txAdicionarEmail.setText("");
            txAdicionarEmail.showPLaceHolder();
            txAdicionarTelefone.setText("");
            txAdicionarTelefone.showPLaceHolder();
            if (jComboBoxAdicionarFuncao.getModel().getSize() > 0) {
                jComboBoxAdicionarFuncao.setSelectedIndex(0);
            }
            txAdicionarIdentificacao.setText("");
            txAdicionarTelefone.showPLaceHolder();
            selecionado = null;
            txAdicionarTelefone.restartPlaceHolder();
            txAdicionarEmail.restartPlaceHolder();
            txAdicionarNome.restartPlaceHolder();
            txAdicionarIdentificacao.restartPlaceHolder();
            jSpinnerAdicionarPrivilegio.setValue(1);
        }
        jTableUtilizadores.clearSelection();
        jButtonReiniciar.setVisible(false);
        jLabelAdicionarNome.requestFocus();
        try {
            if (Clavis.KeyQuest.class.getResource("Images/save.png") != null) {
                BufferedImage bfsave = ImageIO.read(Clavis.KeyQuest.class.getResourceAsStream("Images/save.png"));
                ImageIcon imsave = new ImageIcon(bfsave);
                jButtonAdicionarGuardar.setIcon(imsave);
            } else {
                jButtonAdicionarGuardar.setText(lingua.translate("Guardar"));
            }
        } catch (IOException e) {
        }
        jButtonAdicionarGuardar.setToolTipText(lingua.translate("Registar novo utilizador") + ".");
        jLabelTituloAdicionar.setText(lingua.translate("Adicionar utilizador"));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WUsers s = new WUsers(Color.WHITE, Color.CYAN, "", Locale.getLocale_pt_PT(), true, null);
                s.create();
                s.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarGuardar;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JComboBox<String> jComboBoxAdicionarFuncao;
    private javax.swing.JLabel jLabelAdicionarEmail;
    private javax.swing.JLabel jLabelAdicionarFuncao;
    private javax.swing.JLabel jLabelAdicionarIdentificacao;
    private javax.swing.JLabel jLabelAdicionarNome;
    private javax.swing.JLabel jLabelAdicionarPrivilegio;
    private javax.swing.JLabel jLabelAdicionarTelefone;
    private javax.swing.JLabel jLabelEditar;
    private javax.swing.JLabel jLabelTituloAdicionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JScrollPane jScrollPaneUtilizadores;
    private javax.swing.JSpinner jSpinnerAdicionarPrivilegio;
    /*
    private javax.swing.JTable jTableUtilizadores;
    */
    private org.jdesktop.swingx.JXTable jTableUtilizadores;
    private Components.PersonalTextField txAdicionarEmail;
    private Components.PersonalTextField txAdicionarIdentificacao;
    private Components.PersonalTextField txAdicionarNome;
    private Components.PersonalTextField txAdicionarTelefone;
    private Components.PersonalTextField txPesquisa;
    // End of variables declaration//GEN-END:variables
}
